// The Android Gradle Plugin builds the native code with the Android NDK.

group 'com.flutter_rust_bridge.tma_core'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // The Android Gradle Plugin knows how to build native code with the NDK.
        classpath 'com.android.tools.build:gradle:7.3.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    if (project.android.hasProperty("namespace")) {
        namespace 'com.flutter_rust_bridge.tma_core'
    }

    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    defaultConfig {
        minSdkVersion flutter.minSdkVersion
    }
}

apply from: "../cargokit/gradle/plugin.gradle"
cargokit {
    manifestDir = "../../tma_core"
    libname = "tma_core"
}
