// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SecondDuration`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `source`, `source`, `source`

void initPlayer() => RustLib.instance.api.crateApiAudioInitPlayer();

Future<void> loadAudioSourceAndPlay({
  required String url,
  required String jwtValue,
}) => RustLib.instance.api.crateApiAudioLoadAudioSourceAndPlay(
  url: url,
  jwtValue: jwtValue,
);

/// Retrun value means is_paused
bool playOrPauseAudio() => RustLib.instance.api.crateApiAudioPlayOrPauseAudio();

void stopAudio() => RustLib.instance.api.crateApiAudioStopAudio();

double? getTotalDuration() =>
    RustLib.instance.api.crateApiAudioGetTotalDuration();

double getPosition() => RustLib.instance.api.crateApiAudioGetPosition();

void trySeek({required double position}) =>
    RustLib.instance.api.crateApiAudioTrySeek(position: position);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InitPlayerError>>
abstract class InitPlayerError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoadAudioSourceError>>
abstract class LoadAudioSourceError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlayAudioError>>
abstract class PlayAudioError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SeekError>>
abstract class SeekError implements RustOpaqueInterface {}
